import { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { Badge, Box, Button, Container, Flex, Heading, Input, Progress, Table, TableContainer, Tbody, Td, Text, Th, Thead, Tr } from '@chakra-ui/react';

const CourseRoster = () => {
  const { id } = useParams();
  const [courseTitle, setCourseTitle] = useState('');
  const [students, setStudents] = useState([{ id: 's101', name: 'Jane Doe', email: 'jane.doe@student.edu', date: 'Aug 15, 2026', progress: 85 }, { id: 's102', name: 'John Smith', email: 'john.smith@student.edu', date: 'Aug 16, 2026', progress: 40 }, { id: 's103', name: 'Alice Johnson', email: 'alice.j@student.edu', date: 'Aug 20, 2026', progress: 100 }, { id: 's104', name: 'Bob Williams', email: 'bwilliams@student.edu', date: 'Sep 01, 2026', progress: 15 }]);
  const [searchTerm, setSearchTerm] = useState('');
  useEffect(() => { const mockCourseNames = { fs202: 'Full Stack Development', ds300: 'Data Structures', cs101: 'Intro to Computer Science' }; // eslint-disable-next-line react-hooks/set-state-in-effect
    setCourseTitle(mockCourseNames[id] || 'Course Details'); }, [id]);
  const filteredStudents = students.filter(student => student.name.toLowerCase().includes(searchTerm.toLowerCase()) || student.email.toLowerCase().includes(searchTerm.toLowerCase()));
  const handleDropStudent = (studentId, studentName) => { if (window.confirm(`Are you sure you want to remove ${studentName} from this course?`)) setStudents(students.filter(s => s.id !== studentId)); };
  return <Container maxW="container.xl" py={10}><Flex justify="space-between" align={{ base: 'start', md: 'center' }} direction={{ base: 'column', md: 'row' }} gap={4} mb={8}><Box><Badge colorScheme="red" mb={2}>Faculty Portal</Badge><Heading size="lg">Student Roster</Heading><Text color="gray.400">{courseTitle} ({id.toUpperCase()})</Text></Box><Button as={Link} to="/admin/courses" variant="outline">Back to Catalog</Button></Flex><Box bg="gray.800" rounded="lg" overflow="hidden"><Flex p={5} justify="space-between" align="center" gap={4} wrap="wrap"><Input maxW="lg" placeholder="Search students by name or email..." value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} /><Text color="gray.400" fontWeight="bold">Total Enrolled: {students.length}</Text></Flex><TableContainer><Table><Thead><Tr><Th>Student Name</Th><Th>Email Address</Th><Th>Enrollment Date</Th><Th>Course Progress</Th><Th isNumeric>Actions</Th></Tr></Thead><Tbody>{filteredStudents.length === 0 ? <Tr><Td colSpan={5} textAlign="center" py={12} color="gray.400">No students found matching "{searchTerm}"</Td></Tr> : filteredStudents.map(student => <Tr key={student.id}><Td fontWeight="bold">{student.name}</Td><Td color="gray.400">{student.email}</Td><Td>{student.date}</Td><Td minW="180px"><Flex justify="space-between" fontSize="sm" mb={1}><Text>{student.progress}%</Text>{student.progress === 100 && <Badge colorScheme="green">Complete</Badge>}</Flex><Progress value={student.progress} colorScheme={student.progress === 100 ? 'green' : 'brand'} size="sm" /></Td><Td isNumeric><Button onClick={() => handleDropStudent(student.id, student.name)} size="sm" variant="outline" colorScheme="red" aria-label={`Drop ${student.name}`}>Drop Student</Button></Td></Tr>)}</Tbody></Table></TableContainer></Box></Container>;
};
export default CourseRoster;
